name: UpdraftPlugin
version: '${project.version}'
main: xyz.ki3ragi.updraftplugin.UpdraftPlugin
api-version: '1.20'
commands:
  setupdraftspeed:
    description: 上昇速度を設定します。
    usage: /setupdraftspeed <速度>